# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Mar  7 19:42:35 2011
#      by: pyside-uic 0.2.7 running on PySide 1.0.0~rc1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 431)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/polygon-area.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 25))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName("helpMenu")
        self.editMenu = QtGui.QMenu(self.menubar)
        self.editMenu.setObjectName("editMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.newAction = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/document-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newAction.setIcon(icon1)
        self.newAction.setObjectName("newAction")
        self.openAction = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openAction.setIcon(icon2)
        self.openAction.setObjectName("openAction")
        self.recentsFormsAction = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/document-open-recent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recentsFormsAction.setIcon(icon3)
        self.recentsFormsAction.setObjectName("recentsFormsAction")
        self.saveAction = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAction.setIcon(icon4)
        self.saveAction.setObjectName("saveAction")
        self.saveAsAction = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/document-save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAsAction.setIcon(icon5)
        self.saveAsAction.setObjectName("saveAsAction")
        self.printAction = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/document-print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printAction.setIcon(icon6)
        self.printAction.setObjectName("printAction")
        self.saveImageAction = QtGui.QAction(MainWindow)
        self.saveImageAction.setObjectName("saveImageAction")
        self.closeAction = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/dialog-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAction.setIcon(icon7)
        self.closeAction.setObjectName("closeAction")
        self.quitAction = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon8)
        self.quitAction.setObjectName("quitAction")
        self.undoAction = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoAction.setIcon(icon9)
        self.undoAction.setObjectName("undoAction")
        self.redoAction = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoAction.setIcon(icon10)
        self.redoAction.setObjectName("redoAction")
        self.preferencesAction = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.preferencesAction.setIcon(icon11)
        self.preferencesAction.setObjectName("preferencesAction")
        self.action_Cut = QtGui.QAction(MainWindow)
        self.action_Cut.setObjectName("action_Cut")
        self.pasteAction = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasteAction.setIcon(icon12)
        self.pasteAction.setObjectName("pasteAction")
        self.copyAction = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyAction.setIcon(icon13)
        self.copyAction.setObjectName("copyAction")
        self.action_Paste_Cut = QtGui.QAction(MainWindow)
        self.action_Paste_Cut.setObjectName("action_Paste_Cut")
        self.deleteAction = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteAction.setIcon(icon14)
        self.deleteAction.setObjectName("deleteAction")
        self.cutAction = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cutAction.setIcon(icon15)
        self.cutAction.setObjectName("cutAction")
        self.selectAllAction = QtGui.QAction(MainWindow)
        self.selectAllAction.setObjectName("selectAllAction")
        self.findAction = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findAction.setIcon(icon16)
        self.findAction.setObjectName("findAction")
        self.findAgainAction = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/edit-find-replace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findAgainAction.setIcon(icon17)
        self.findAgainAction.setObjectName("findAgainAction")
        self.polygonAreaHelpAction = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/help-contents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polygonAreaHelpAction.setIcon(icon18)
        self.polygonAreaHelpAction.setObjectName("polygonAreaHelpAction")
        self.releaseNotesAction = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/view-pim-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.releaseNotesAction.setIcon(icon19)
        self.releaseNotesAction.setObjectName("releaseNotesAction")
        self.aboutPolygonAreaAction = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/help-about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutPolygonAreaAction.setIcon(icon20)
        self.aboutPolygonAreaAction.setObjectName("aboutPolygonAreaAction")
        self.reportBugsAction = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/media/default/32x32/icons/kbugbuster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportBugsAction.setIcon(icon21)
        self.reportBugsAction.setObjectName("reportBugsAction")
        self.fileMenu.addAction(self.newAction)
        self.fileMenu.addAction(self.openAction)
        self.fileMenu.addAction(self.recentsFormsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.saveAction)
        self.fileMenu.addAction(self.saveAsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.printAction)
        self.fileMenu.addAction(self.saveImageAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.closeAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.quitAction)
        self.helpMenu.addAction(self.polygonAreaHelpAction)
        self.helpMenu.addAction(self.releaseNotesAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.reportBugsAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.aboutPolygonAreaAction)
        self.editMenu.addAction(self.undoAction)
        self.editMenu.addAction(self.redoAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.cutAction)
        self.editMenu.addAction(self.copyAction)
        self.editMenu.addAction(self.pasteAction)
        self.editMenu.addAction(self.deleteAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.selectAllAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.findAction)
        self.editMenu.addAction(self.findAgainAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.preferencesAction)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Polygon Area", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.newAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.openAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.recentsFormsAction.setText(QtGui.QApplication.translate("MainWindow", "Recents forms", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsAction.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.printAction.setText(QtGui.QApplication.translate("MainWindow", "&Print", None, QtGui.QApplication.UnicodeUTF8))
        self.printAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.saveImageAction.setText(QtGui.QApplication.translate("MainWindow", "Save &image...", None, QtGui.QApplication.UnicodeUTF8))
        self.closeAction.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.closeAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.undoAction.setText(QtGui.QApplication.translate("MainWindow", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.undoAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.redoAction.setText(QtGui.QApplication.translate("MainWindow", "&Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.preferencesAction.setText(QtGui.QApplication.translate("MainWindow", "Prefere&nces", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setText(QtGui.QApplication.translate("MainWindow", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.pasteAction.setText(QtGui.QApplication.translate("MainWindow", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.pasteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.copyAction.setText(QtGui.QApplication.translate("MainWindow", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.copyAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Paste_Cut.setText(QtGui.QApplication.translate("MainWindow", "&Paste&Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAction.setText(QtGui.QApplication.translate("MainWindow", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.cutAction.setText(QtGui.QApplication.translate("MainWindow", "&Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.cutAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllAction.setText(QtGui.QApplication.translate("MainWindow", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.findAction.setText(QtGui.QApplication.translate("MainWindow", "&Find", None, QtGui.QApplication.UnicodeUTF8))
        self.findAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.findAgainAction.setText(QtGui.QApplication.translate("MainWindow", "Find A&gain", None, QtGui.QApplication.UnicodeUTF8))
        self.findAgainAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.polygonAreaHelpAction.setText(QtGui.QApplication.translate("MainWindow", "Polygon Area &Help", None, QtGui.QApplication.UnicodeUTF8))
        self.polygonAreaHelpAction.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.releaseNotesAction.setText(QtGui.QApplication.translate("MainWindow", "Release &Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutPolygonAreaAction.setText(QtGui.QApplication.translate("MainWindow", "&About Polygon Area", None, QtGui.QApplication.UnicodeUTF8))
        self.reportBugsAction.setText(QtGui.QApplication.translate("MainWindow", "&Report Bugs...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

